CREATE TABLE [dbo].[ItensReceita] (
    [id]                                        NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [id_receita]                                INT          NOT NULL,
    [etapa]                                     VARCHAR (50) NULL,
    [processo]                                  VARCHAR (50) NULL,
    [produto]                                   VARCHAR (50) NULL,
    [rele]                                      INT          NULL,
    [tipo_evento_anterior]                      VARCHAR (50) NULL,
    [tempo_espera_evento_anterior]              TIME (0)     NULL,
    [entrada_evento_anterior]                   VARCHAR (50) NULL,
    [status_entrada_digital_evento_anterior]    BIT          NULL,
    [temperatura_evento_anterior]				INT          NULL,
    [tipo_evento_posterior]                     VARCHAR (50) NULL,
	[pre_corte]                                 VARCHAR (50) NULL,
    [corte]                                     VARCHAR (50) NULL,
    [tempo_on]                                  INT          NULL,
    [tempo_off]                                 INT          NULL,
    [limite_peso_seguranca_evento_posterior]    VARCHAR (50) NULL,
    [entrada_evento_posterior]                  VARCHAR (50) NULL,
    [status_entrada_digital_evento_posterior]   BIT          NULL,
    [temperatura_evento_posterior]				INT			 NULL,
    [limite_temperatura_evento_posterior]       INT			 NULL,
    [tempo_evento_posterior]                    TIME(0)		 NULL,
    [tempo_segurança_evento_posterior]          TIME(0)      NULL,
    [tempo_limite_total]						TIME(0)      NULL,
    [alerta_emergencia]                         BIT          NULL,
    [pausar_receita]                            BIT          NULL,
    [acionar_saida]                             INT          NULL,
    [saida_seguranca]							BIT          NULL,
    [sequencia]                                 INT          NULL,
    [dateinsert]                                DATETIME     NULL,
    [dateupdate]                                DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

