CREATE TABLE [dbo].[ItensReceita] (
    [id]                                        NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [id_receita]                                INT          NOT NULL,
    [etapa]                                     VARCHAR (50) NULL,
    [processo]                                  VARCHAR (50) NULL,
    [produto]                                   VARCHAR (50) NULL,
    [rele]                                      INT NULL,
    [tipo_evento_anterior]                      VARCHAR (50) NULL,
    [tempo_espera]                              DATETIME NULL,
    [entrada_evento_anterior]                   VARCHAR (50) NULL,
    [status_entrada_evento_anterior]            BIT NULL,
    [valor_temperatura_evento_anterior]         INT NULL,
    [limite_de_temperatura_evento_anterior]     INT NULL,
    [tipo_evento_posterior]                     VARCHAR (50) NULL,
    [pre_corte]                                 VARCHAR (50) NULL,
    [corte]                                     VARCHAR (50) NULL,
    [tempo_on]                                  INT NULL,
    [tempo_off]                                 INT NULL,
    [limite_peso_seguranca]                     VARCHAR (50) NULL,
    [entrada_evento_posterior]                  VARCHAR (50) NULL,
    [status_entrada_evento_posterior]           BIT NULL,
    [valor_temperatura_evento_posterior]        VARCHAR (50) NULL,
    [limite_de_temperatura_evento_posterior]    VARCHAR (50) NULL,
    [segurança_de_temperatura_evento_posterior] VARCHAR (50) NULL,
    [tempo_evento_anterior]                     VARCHAR (50) NULL,
    [segurança_tempo_evento_posterior]          VARCHAR (50) NULL,
    [tempo_limite_segurança]                    VARCHAR (50) NULL,
    [alerta_emergencia]                         BIT NULL,
    [pausar_receita]                            BIT NULL,
    [acionar_saida]                             INT NULL,
    [saida_emergencia]                          BIT NULL,
    [dateinsert]                                DATETIME     NULL,
    [dateupdate]                                DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

